openapi: 3.0.1
info:
  title: WAFW00F API
  version: 1.0.0
  description: API for detecting WAF solutions using wafw00f.
servers:
  - url: https://wafw00f.kscsc.online/api
paths:
  /trigger_waf_woof:
    post:
      summary: Detect WAF solution for a target URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                target:
                  type: string
                  description: Target URL to scan (must start with http:// or https://)
              required:
                - target
      responses:
        '200':
          description: WAF detection result
          content:
            application/json:
              schema:
                type: object
                properties:
                  target:
                    type: string
                    example: https://contact.kscsc.online
                  status:
                    type: string
                    example: protected
                  solution:
                    oneOf:
                      - type: string
                      - type: array
                        items:
                          type: string
                    example: ["Cloudflare (Cloudflare Inc.)"]
        '400':
          description: Bad request (invalid input)
          content:
            text/plain:
              schema:
                type: string
    get:
      summary: Get OpenAPI specification in YAML format
      responses:
        '200':
          description: OpenAPI YAML specification
          content:
            application/yaml:
              schema:
                type: string