name: Deploy Python project to Azure Function App

permissions:
  checks: write
  id-token: write

on:
  push:
    branches: 
      - "main"

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './function'
  PYTHON_VERSION: '3.12'
  RESOURCE_GROUP: 'WafW00f'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check files
        run: |
          pwd
          ls -la
          ls -la bicep

      - name: Validate Bicep Template
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: validate
          name: Validate Bicep Template
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ env.RESOURCE_GROUP }}
          template-file: bicep/main.bicep

      - name: Deploy Bicep Template
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: craete
          name: Validate Bicep Template
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ env.RESOURCE_GROUP }}
          template-file: bicep/main.bicep\
          parameters: >
            {
              "functionAppName":"${{ secrets.AZURE_FUNCTIONAPP_NAME }}",
              "logAnalyticsWorkspaceId":"${{ secrets.AZURE_LOG_ANALYTICS_WORKSPACE_ID }}"
            }

      # DAST
      - name: 'Dastardly Scan Action'
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://${{secrets.AZURE_FUNCTIONAPP_NAME}}.kscsc.online/'

      - name: 'Publish Test Report'
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/dastardly-report.xml'
          require_tests: true