name: Deploy Python project to Azure Function App

permissions:
  checks: write
  id-token: write

on:
  push:
    branches: 
      - "main"

env:
  AZURE_FUNCTIONAPP_NAME: 'wafw00fkscsc'      # Function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './function' # Path to function app project
  PYTHON_VERSION: '3.11'                      # Python version to use
  RESOURCE_GROUP: 'WafW00f'                   # Resource group name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy Azure Infrastructure'
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./bicep/function.bicep
          failOnStdErr: false

      - name: 'Deploy Function Code'
        run: |
          cd function
          pip3 install -r requirements.txt -t .python_packages/lib/site-packages/
          zip -r functionapp.zip ./*
          az storage blob upload --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --container-name functionapp --name functionapp.zip --file ./function.zip --auth-mode login

      # DAST
      - name: 'Dastardly Scan Action'
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://wafw00f.kscsc.online/'

      - name: 'Publish Test Report'
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/dastardly-report.xml'
          require_tests: true