name: Deploy Python project to Azure Function App

permissions:
  id-token: write

on:
  push:
    branches: 
      - "main"

env:
  AZURE_FUNCTIONAPP_NAME: 'wafw00fkscsc'      # Function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'         # Path to function app project
  PYTHON_VERSION: '3.11'                      # Python version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Setup Python ${{ env.PYTHON_VERSION }} Environment'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.5.1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true

      # DAST
      - name: 'Dastardly Scan Action'
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://wafw00f.kscsc.online/'

      - name: 'Publish Test Report'
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/dastardly-report.xml'
          require_tests: true